import type { Activity, Island } from "@/modules/core";

export const ISLANDS: Island[] = [
  {
    id: 1,
    name: "Drum Jungle",
    theme: "Wild rhythms and black-key adventure",
    emoji: "🌴",
    color: "#22c55e",
    gradient: "from-emerald-600 via-green-500 to-lime-400",
    guideName: "Tiko the Toucan",
    guideEmoji: "🦜",
    coreSkills: [
      "Keyboard geography",
      "Black-key groups",
      "Finger numbers",
      "High/low",
      "Loud/soft",
      "Steady beat",
    ],
    bossSongId: "jungle-beat",
    activityIds: [
      "i1-explore-keys",
      "i1-black-hop",
      "i1-finger-fun",
      "i1-high-low",
      "i1-loud-soft",
      "i1-beat-tap",
      "i1-echo-jungle",
      "i1-boss-jungle",
    ],
    unlocked: true,
  },
  {
    id: 2,
    name: "Letter Beach",
    theme: "White keys and note names under the sun",
    emoji: "🏖️",
    color: "#38bdf8",
    gradient: "from-sky-500 via-cyan-400 to-amber-200",
    guideName: "Sandy the Seahorse",
    guideEmoji: "🦄",
    coreSkills: [
      "White key names A–G",
      "Middle C home base",
      "Quarter/half/whole rhythms",
    ],
    bossSongId: "c-is-for-castle",
    activityIds: [
      "i2-middle-c",
      "i2-name-race",
      "i2-quarter-clap",
      "i2-half-whole",
      "i2-echo-letters",
      "i2-play-along-c",
      "i2-boss-castle",
    ],
    unlocked: false,
  },
  {
    id: 3,
    name: "Five-Finger Cove",
    theme: "Right-hand melodies in C position",
    emoji: "🏝️",
    color: "#a78bfa",
    gradient: "from-violet-600 via-purple-500 to-fuchsia-400",
    guideName: "Finn the Dolphin",
    guideEmoji: "🐬",
    coreSkills: [
      "Pre-staff notation",
      "RH C-position",
      "Left hand intro",
    ],
    bossSongId: "ode-to-joy-rh",
    activityIds: [
      "i3-c-position",
      "i3-prestaff",
      "i3-melody-line",
      "i3-lh-dips",
      "i3-echo-cove",
      "i3-twinkle",
      "i3-boss-ode",
    ],
    unlocked: false,
  },
  {
    id: 4,
    name: "Staff Mountain",
    theme: "Climb the grand staff with guide notes",
    emoji: "⛰️",
    color: "#94a3b8",
    gradient: "from-slate-600 via-stone-500 to-sky-300",
    guideName: "Gemma the Goat",
    guideEmoji: "🐐",
    coreSkills: ["Grand staff", "Guide notes", "Steps up/down"],
    bossSongId: "mountain-climber",
    activityIds: ["i4-coming-soon"],
    unlocked: false,
  },
  {
    id: 5,
    name: "Melody Meadow",
    theme: "Steps, skips, and sunny tunes",
    emoji: "🌻",
    color: "#fbbf24",
    gradient: "from-yellow-500 via-amber-400 to-lime-300",
    guideName: "Buzz the Bee",
    guideEmoji: "🐝",
    coreSkills: ["Steps & skips", "9-note range", "3/4 vs 4/4"],
    bossSongId: "twinkle-variations",
    activityIds: ["i5-coming-soon"],
    unlocked: false,
  },
  {
    id: 6,
    name: "Two-Hands Harbor",
    theme: "Both hands sail together",
    emoji: "⚓",
    color: "#0ea5e9",
    gradient: "from-blue-700 via-blue-500 to-teal-300",
    guideName: "Captain Coral",
    guideEmoji: "🧜",
    coreSkills: ["Hands together", "Ties", "Dotted half", "Phrasing"],
    bossSongId: "row-your-boat",
    activityIds: ["i6-coming-soon"],
    unlocked: false,
  },
  {
    id: 7,
    name: "Sharp Peaks",
    theme: "Sharps, flats, and icy tempo",
    emoji: "🏔️",
    color: "#e2e8f0",
    gradient: "from-indigo-700 via-slate-400 to-white",
    guideName: "Frost the Fox",
    guideEmoji: "🦊",
    coreSkills: ["G position", "Accidentals", "Eighth notes", "Tempo words"],
    bossSongId: "frozen-peak-march",
    activityIds: ["i7-coming-soon"],
    unlocked: false,
  },
  {
    id: 8,
    name: "Chord Canyon",
    theme: "Triads echo off red rock walls",
    emoji: "🏜️",
    color: "#f97316",
    gradient: "from-orange-700 via-amber-600 to-red-400",
    guideName: "Echo the Lizard",
    guideEmoji: "🦎",
    coreSkills: ["Triads C/F/G", "Dynamics", "Legato/staccato"],
    bossSongId: "canyon-echo",
    activityIds: ["i8-coming-soon"],
    unlocked: false,
  },
  {
    id: 9,
    name: "Scale Falls",
    theme: "Scales cascade like waterfalls",
    emoji: "💦",
    color: "#06b6d4",
    gradient: "from-cyan-700 via-teal-500 to-blue-300",
    guideName: "Ripple the Otter",
    guideEmoji: "🦦",
    coreSkills: ["C & G scales", "LH patterns", "Rests", "Sight-reading"],
    bossSongId: "waterfall-run",
    activityIds: ["i9-coming-soon"],
    unlocked: false,
  },
  {
    id: 10,
    name: "Concert City",
    theme: "Lights, applause, and your big recital",
    emoji: "🎭",
    color: "#ec4899",
    gradient: "from-pink-600 via-rose-500 to-violet-400",
    guideName: "Maestro Max",
    guideEmoji: "🎩",
    coreSkills: ["Full pieces", "Expression", "Memorization", "Sight-reading snack"],
    bossSongId: "graduation-set",
    activityIds: ["i10-coming-soon"],
    unlocked: false,
  },
];

export const ACTIVITIES: Activity[] = [
  // Island 1
  {
    id: "i1-explore-keys",
    islandId: 1,
    type: "free_play",
    title: "Explore the Jungle Keys",
    kidPrompt: "Press any keys! Your companion will dance when it hears you.",
    skillIds: ["geo-black-2", "geo-black-3"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i1-black-hop",
    islandId: 1,
    type: "play_along",
    title: "Black Key Hop",
    kidPrompt: "Hop on the black keys like jungle stones!",
    skillIds: ["geo-black-2", "geo-black-3"],
    songId: "black-key-hop",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i1-finger-fun",
    islandId: 1,
    type: "note_naming",
    title: "Finger Number Fun",
    kidPrompt: "Show me finger 1, 2, 3… on the black keys!",
    skillIds: ["tech-finger-numbers"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i1-high-low",
    islandId: 1,
    type: "echo",
    title: "High & Low Safari",
    kidPrompt: "Is the sound high like a bird or low like a drum?",
    skillIds: ["geo-high-low"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i1-loud-soft",
    islandId: 1,
    type: "echo",
    title: "Loud Roar, Soft Whisper",
    kidPrompt: "Play LOUD like a lion, then soft like a mouse!",
    skillIds: ["dyn-loud-soft"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i1-beat-tap",
    islandId: 1,
    type: "rhythm_tap",
    title: "Jungle Beat Tap",
    kidPrompt: "Tap the beat with the drums — steady as a parade!",
    skillIds: ["rhythm-steady-beat"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i1-echo-jungle",
    islandId: 1,
    type: "echo",
    title: "Echo in the Trees",
    kidPrompt: "Listen, then play what you hear!",
    skillIds: ["geo-black-2", "geo-high-low"],
    songId: "black-key-hop",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i1-boss-jungle",
    islandId: 1,
    type: "boss_song",
    title: "Boss Song: Jungle Beat",
    kidPrompt: "Play the whole Jungle Beat to unlock the boat!",
    skillIds: ["geo-black-2", "geo-black-3", "rhythm-steady-beat"],
    songId: "jungle-beat",
    starsMax: 3,
    estimatedMinutes: 4,
    requires: ["i1-black-hop", "i1-beat-tap"],
  },
  // Island 2
  {
    id: "i2-middle-c",
    islandId: 2,
    type: "note_naming",
    title: "Find Middle C",
    kidPrompt: "Middle C is home base — can you find it every time?",
    skillIds: ["geo-middle-c"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i2-name-race",
    islandId: 2,
    type: "note_naming",
    title: "Letter Name Race",
    kidPrompt: "Name the white keys as fast as a beach crab!",
    skillIds: ["read-white-keys-ag"],
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i2-quarter-clap",
    islandId: 2,
    type: "rhythm_tap",
    title: "Quarter Note Clap",
    kidPrompt: "Clap or tap every beat — ta, ta, ta, ta!",
    skillIds: ["rhythm-quarter"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i2-half-whole",
    islandId: 2,
    type: "rhythm_tap",
    title: "Hold the Waves",
    kidPrompt: "Half notes hold for 2, whole notes hold for 4!",
    skillIds: ["rhythm-half-whole"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i2-echo-letters",
    islandId: 2,
    type: "echo",
    title: "Letter Echo",
    kidPrompt: "Hear a note, then play it back!",
    skillIds: ["read-white-keys-ag", "geo-high-low"],
    songId: "warm-up-cde",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i2-play-along-c",
    islandId: 2,
    type: "play_along",
    title: "Castle Practice",
    kidPrompt: "Follow the falling notes to the castle!",
    skillIds: ["geo-middle-c", "rhythm-quarter"],
    songId: "c-is-for-castle",
    starsMax: 3,
    estimatedMinutes: 4,
  },
  {
    id: "i2-boss-castle",
    islandId: 2,
    type: "boss_song",
    title: "Boss Song: C is for Castle",
    kidPrompt: "Play the whole song to sail to the next island!",
    skillIds: ["read-white-keys-ag", "geo-middle-c", "rhythm-quarter"],
    songId: "c-is-for-castle",
    starsMax: 3,
    estimatedMinutes: 4,
    requires: ["i2-middle-c", "i2-play-along-c"],
  },
  // Island 3
  {
    id: "i3-c-position",
    islandId: 3,
    type: "play_along",
    title: "Right Hand Home",
    kidPrompt: "Fingers rest on C D E F G — that's C position!",
    skillIds: ["tech-c-position-rh"],
    songId: "warm-up-cde",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i3-prestaff",
    islandId: 3,
    type: "note_naming",
    title: "Picture Notes",
    kidPrompt: "Follow the finger numbers on the chart!",
    skillIds: ["read-prestaff"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i3-melody-line",
    islandId: 3,
    type: "play_along",
    title: "Cove Melody",
    kidPrompt: "Play a smooth melody with your right hand.",
    skillIds: ["tech-c-position-rh", "read-prestaff"],
    songId: "ode-to-joy-rh",
    starsMax: 3,
    estimatedMinutes: 4,
  },
  {
    id: "i3-lh-dips",
    islandId: 3,
    type: "echo",
    title: "Left Hand Dips",
    kidPrompt: "Give your left hand a turn in the water!",
    skillIds: ["tech-lh-intro"],
    starsMax: 3,
    estimatedMinutes: 2,
  },
  {
    id: "i3-echo-cove",
    islandId: 3,
    type: "echo",
    title: "Cove Echo",
    kidPrompt: "Listen carefully — then copy the tune!",
    skillIds: ["tech-c-position-rh", "geo-high-low"],
    songId: "twinkle-snippet",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i3-twinkle",
    islandId: 3,
    type: "play_along",
    title: "Twinkle Practice",
    kidPrompt: "A little twinkle before the big boss!",
    skillIds: ["tech-c-position-rh"],
    songId: "twinkle-snippet",
    starsMax: 3,
    estimatedMinutes: 3,
  },
  {
    id: "i3-boss-ode",
    islandId: 3,
    type: "boss_song",
    title: "Boss Song: Ode to Joy",
    kidPrompt: "Play Ode to Joy with your right hand — you've got this!",
    skillIds: ["tech-c-position-rh", "read-prestaff"],
    songId: "ode-to-joy-rh",
    starsMax: 3,
    estimatedMinutes: 5,
    requires: ["i3-c-position", "i3-melody-line"],
  },
  // Scaffold placeholders for islands 4–10
  ...[4, 5, 6, 7, 8, 9, 10].map(
    (id): Activity => ({
      id: `i${id}-coming-soon`,
      islandId: id,
      type: "play_along",
      title: "Coming Soon Adventure",
      kidPrompt: "This island is still being built — check back after the next update!",
      skillIds: [],
      starsMax: 3,
      estimatedMinutes: 1,
    }),
  ),
];

export function getIsland(id: number): Island | undefined {
  return ISLANDS.find((i) => i.id === id);
}

export function getActivity(id: string): Activity | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}

export function activitiesForIsland(islandId: number): Activity[] {
  return ACTIVITIES.filter((a) => a.islandId === islandId);
}

/** Band members recruited per island (collection mechanic) */
export const BAND_MEMBERS: Record<number, { id: string; name: string; emoji: string }> = {
  1: { id: "drum-monkey", name: "Boomy the Monkey", emoji: "🐵" },
  2: { id: "shell-singer", name: "Shelly the Singer", emoji: "🐚" },
  3: { id: "coral-keys", name: "Coral on Keys", emoji: "🐠" },
  4: { id: "mountain-horn", name: "Horny the Goat", emoji: "🐏" },
  5: { id: "meadow-flute", name: "Pip the Cricket", emoji: "🦗" },
  6: { id: "harbor-bass", name: "Bass the Whale", emoji: "🐋" },
  7: { id: "peak-bells", name: "Jingle Fox", emoji: "🔔" },
  8: { id: "canyon-guitar", name: "Strummer Lizard", emoji: "🎸" },
  9: { id: "falls-harp", name: "Harpy Otter", emoji: "🦦" },
  10: { id: "city-maestro", name: "City Maestro", emoji: "🎻" },
};
